version: '3.9'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: adm
      MYSQL_USER: docker
      MYSQL_PASSWORD: adm
      MYSQL_DATABASE: book_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - rperatello-network
  book-api:
    image: rperatello/book-api
    restart: always
    build: ./book-api
    working_dir: /book-api
    environment:
      SERVER_PORT: 80
      CORS_ORIGIN_PATTERNS: http://localhost:8080,http://localhost:8081
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/book_db?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: adm
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_SHOW_SQL: false
      SPRING_JPA_OPEN_IN_VIEW: true
      TZ: America/Sao_Paulo
      MEMCACHED_HOST: memcached
      FILE_CSV_PATH: "/app/fileCSV/Books_df.csv"
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - rperatello-network
  memcached:
    image: memcached:1.6.31-alpine
    ports:
      - 11211:11211
    expose:
      - 11211
    networks:
      - rperatello-network
networks:
  rperatello-network:
    driver: bridge