server:
  port: 8081
cors:
  originPatterns: http://localhost:8080,http://localhost:8081
spring:
  application:
    name: book-api
  datasource:
    url: jdbc:h2:mem:book_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    driverClassName: org.h2.Driver
    username: sa
    password:  
    connectionProperties: useUnicode=true;characterEncoding=UTF-8      
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none    
    show-sql: false
