server:
  port: ${SERVER_PORT:80}
cors:
  originPatterns: ${CORS_ORIGIN_PATTERNS:http://127.0.0.1:8080,http://127.0.0.1:8081}
spring:
  application:
    name: book-api
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/book_db?useTimezone=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:adm}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:true}
springdoc:
  pathsToMatch: 
  - /auth/**
  - /api/v1/**
  swagger-ui:
    use-root-path: true