spring:
  application:
    name: book-api
  datasource:
    url: jdbc:h2:mem:book_db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:        
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none    
    show-sql: false
